name: lije
description: A pregnancy tracking app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  android_alarm_manager_plus: ^4.0.4
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lije.gif
    - assets/lije.png
    - assets/lije_logo.png
    - assets/nobg.png
    - assets/pregnancy.png
    - assets/afterpreg.png
    - assets/birthdate.png
    - assets/mother.jpeg
    - assets/baby.jpeg
    - assets/all.jpeg
